/**
 * Dimension Engine — generates dimension annotations for 2D drawing views.
 */

export interface Dimension {
  id: string;
  type: "linear" | "angular" | "radial" | "diameter";
  /** Start point of dimension line */
  x1: number; y1: number;
  /** End point of dimension line */
  x2: number; y2: number;
  /** Value to display */
  value: number;
  /** Display text (e.g., "25.00") */
  text: string;
  /** Offset distance for dimension line from geometry */
  offset: number;
  /** Label position */
  labelX: number; labelY: number;
}

let dimCounter = 0;

/**
 * Create a linear dimension between two points.
 */
export function createLinearDimension(
  x1: number, y1: number,
  x2: number, y2: number,
  offset: number = 15
): Dimension {
  const dist = Math.hypot(x2 - x1, y2 - y1);
  const mx = (x1 + x2) / 2;
  const my = (y1 + y2) / 2;

  // Perpendicular offset for dimension line
  const dx = x2 - x1;
  const dy = y2 - y1;
  const len = Math.hypot(dx, dy) || 1;
  const nx = -dy / len;
  const ny = dx / len;

  return {
    id: `dim_${++dimCounter}`,
    type: "linear",
    x1, y1, x2, y2,
    value: dist,
    text: dist.toFixed(2),
    offset,
    labelX: mx + nx * offset,
    labelY: my + ny * offset,
  };
}

/**
 * Create a radial dimension for a circle.
 */
export function createRadialDimension(
  cx: number, cy: number,
  radius: number
): Dimension {
  return {
    id: `dim_${++dimCounter}`,
    type: "radial",
    x1: cx, y1: cy,
    x2: cx + radius, y2: cy,
    value: radius,
    text: `R${radius.toFixed(2)}`,
    offset: 0,
    labelX: cx + radius * 0.7,
    labelY: cy - 8,
  };
}

/**
 * Auto-generate dimensions from projected view edges.
 * Picks the overall width and height as primary dimensions.
 */
export function autoGenerateDimensions(
  bounds: { minX: number; minY: number; maxX: number; maxY: number },
  offset: number = 20
): Dimension[] {
  const dims: Dimension[] = [];

  // Width dimension (bottom)
  dims.push(createLinearDimension(
    bounds.minX, bounds.maxY + offset,
    bounds.maxX, bounds.maxY + offset,
    offset
  ));

  // Height dimension (right)
  dims.push(createLinearDimension(
    bounds.maxX + offset, bounds.minY,
    bounds.maxX + offset, bounds.maxY,
    offset
  ));

  return dims;
}
