export {
  type ViewDirection, type ProjectedEdge, type ProjectedView,
  projectMesh, generateStandard3View,
  applyHiddenLineRemoval,
  type SectionView, type SectionLine, generateSectionView,
  type DetailView, generateDetailView,
} from "./projection-engine";

export {
  type Dimension,
  createLinearDimension, createRadialDimension,
  autoGenerateDimensions,
} from "./dimension-engine";

export {
  type GDTSymbol, type GDTCategory, type FeatureControlFrame,
  type MaterialCondition, type DatumReference,
  type WeldingSymbol, type SurfaceFinishSymbol, type SurfaceFinishAnnotation,
  GDT_SYMBOLS,
  createFeatureControlFrame, renderFeatureControlFrame,
  getSymbolsByCategory,
} from "./gdt-symbols";

export { renderDrawingToCanvas, exportDrawingPNG } from "./pdf-export";
