"use client";

import { useState, useRef, useEffect } from "react";
import { useCADState } from "@/lib/store";
import { generateStandard3View, type ProjectedView } from "@/lib/drawing/projection-engine";
import { autoGenerateDimensions, type Dimension } from "@/lib/drawing/dimension-engine";
import { renderDrawingToCanvas, exportDrawingPNG, type DrawingSheet } from "@/lib/drawing/pdf-export";

export function DrawingViewer() {
  const { features } = useCADState();
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const [views, setViews] = useState<ProjectedView[]>([]);
  const [generated, setGenerated] = useState(false);

  const generateDrawing = () => {
    const meshFeature = features.find((f) => f.mesh && f.mesh.vertices.length > 0);
    if (!meshFeature?.mesh) return;

    const projectedViews = generateStandard3View(meshFeature.mesh, 30);
    setViews(projectedViews);
    setGenerated(true);

    // Render to canvas
    if (canvasRef.current) {
      const dims = projectedViews.length > 0
        ? autoGenerateDimensions(projectedViews[0].bounds, 15)
        : [];

      const sheet: DrawingSheet = {
        title: meshFeature.name || "GestureCAD Drawing",
        views: projectedViews,
        dimensions: dims,
        paperWidth: 297, // A4 landscape
        paperHeight: 210,
        scale: "1:1",
        author: "GestureCAD",
        date: new Date().toISOString().split("T")[0],
      };

      renderDrawingToCanvas(sheet, canvasRef.current);
    }
  };

  const handleExport = () => {
    const meshFeature = features.find((f) => f.mesh && f.mesh.vertices.length > 0);
    if (!meshFeature?.mesh || views.length === 0) return;

    const dims = autoGenerateDimensions(views[0].bounds, 15);
    exportDrawingPNG({
      title: meshFeature.name || "GestureCAD Drawing",
      views,
      dimensions: dims,
      paperWidth: 297,
      paperHeight: 210,
      scale: "1:1",
      author: "GestureCAD",
      date: new Date().toISOString().split("T")[0],
    });
  };

  const hasMesh = features.some((f) => f.mesh && f.mesh.vertices.length > 0);

  return (
    <div style={styles.container}>
      <div style={styles.toolbar}>
        <span style={styles.label}>TechDraw</span>
        <button
          style={{ ...styles.btn, opacity: hasMesh ? 1 : 0.4 }}
          onClick={hasMesh ? generateDrawing : undefined}
        >
          Generate 3-View
        </button>
        {generated && (
          <button style={styles.btn} onClick={handleExport}>
            Export PNG
          </button>
        )}
      </div>
      <div style={styles.canvasWrap}>
        <canvas
          ref={canvasRef}
          style={styles.canvas}
          width={891}
          height={630}
        />
        {!generated && (
          <div style={styles.placeholder}>
            Create a 3D feature, then click "Generate 3-View" to create a technical drawing
          </div>
        )}
      </div>
    </div>
  );
}

const styles: Record<string, React.CSSProperties> = {
  container: {
    display: "flex",
    flexDirection: "column",
    height: "100%",
    background: "#f5f5f5",
  },
  toolbar: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "6px 12px",
    background: "#fff",
    borderBottom: "1px solid #ddd",
  },
  label: { fontWeight: 700, fontSize: 13, color: "#333" },
  btn: {
    padding: "5px 12px",
    background: "#3b82f6",
    border: "none",
    borderRadius: 4,
    color: "#fff",
    cursor: "pointer",
    fontFamily: "inherit",
    fontSize: 12,
    fontWeight: 500,
  },
  canvasWrap: {
    flex: 1,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
    overflow: "auto",
  },
  canvas: {
    border: "1px solid #ccc",
    background: "#fff",
    maxWidth: "100%",
    maxHeight: "100%",
  },
  placeholder: {
    position: "absolute",
    color: "#999",
    fontSize: 14,
    textAlign: "center",
  },
};
